name: Deploy-IAC

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '*'
  pull_request:
    branches:
      - dev
      - main


jobs:
  deploy:
    name: check bicep
    runs-on: ubuntu-latest
    env:
      CONFIG_FILE: ${{ github.ref == 'refs/heads/main' && './configprd.yml' || './configdev.yml' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

