name: Deploy-IAC

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '*'
  pull_request:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CONFIG_FILE: ${{ github.ref == 'refs/heads/main' && './configprd.yml' || './configdev.yml' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/CLI@v1

      - name: Check Bicep syntax
        run: |
          echo "Checking bicep syntax..."
          az bicep build --file ./iac-adb-360/main.bicep
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'

      - name: Validate Bicep against Azure
        run: |
          echo "Validating Bicep against Azure..."
          # Add your validation commands here
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'