name: InitPipeline

on:
  push:
    branches:
      - dev
    paths:
      - '*'
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  ENV: ${{ github.ref_name }}

jobs:
  validate-deploy-bundles:
    name: Validate Deploy Bundles
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      - name: Install Databricks CLI v2
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Login to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
            
      - name: Validate Bundle
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            cd bundle_adb_360
            databricks bundle validate

      - name: Deploy Bundle
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            ./bundle_adb_360/helpers/bundle-deploy.sh ${{ vars.RESOURCE_GROUP }} ${{ vars.TENANT_ID }} ${{ vars.CLIENT_ID }} ${{ secrets.CLIENT_SECRET }} ${{ env.ENV }}



